name: ld26_minimalism
description: A sample web application
author: Dennis.Kaselow+ld@gmail.com
dependencies:
  browser: any
  dartemis: any
  lawndart: any
  simple_audio:
    path: ../simple_audio
  dart_to_js_script_rewriter: any
transformers:
- dart_to_js_script_rewriter